//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HUM.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HUM.Globalization.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string DownloadTaskStatus_Canceled {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string DownloadTaskStatus_Downloaded {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DownloadTaskStatus_Error {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string DownloadTaskStatus_Finished {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string DownloadTaskStatus_Pending {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        public static string DownloadTaskStatus_Processed {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string DownloadTaskStatus_Read {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FileType_ImageFile {
            get {
                return ResourceManager.GetString("FileType_ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string FileType_XmlFile {
            get {
                return ResourceManager.GetString("FileType_XmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena Details.
        /// </summary>
        public static string XmlFileType_ArenaDetails {
            get {
                return ResourceManager.GetString("XmlFileType_ArenaDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatars.
        /// </summary>
        public static string XmlFileType_Avatars {
            get {
                return ResourceManager.GetString("XmlFileType_Avatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Token.
        /// </summary>
        public static string XmlFileType_CheckToken {
            get {
                return ResourceManager.GetString("XmlFileType_CheckToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string XmlFileType_Club {
            get {
                return ResourceManager.GetString("XmlFileType_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall Of Fame Players.
        /// </summary>
        public static string XmlFileType_HallOfFamePlayers {
            get {
                return ResourceManager.GetString("XmlFileType_HallOfFamePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Details.
        /// </summary>
        public static string XmlFileType_LeagueDetails {
            get {
                return ResourceManager.GetString("XmlFileType_LeagueDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Fixtures.
        /// </summary>
        public static string XmlFileType_LeagueFixtures {
            get {
                return ResourceManager.GetString("XmlFileType_LeagueFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Compendium.
        /// </summary>
        public static string XmlFileType_ManagerCompendium {
            get {
                return ResourceManager.GetString("XmlFileType_ManagerCompendium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Archive.
        /// </summary>
        public static string XmlFileType_MatchArchive {
            get {
                return ResourceManager.GetString("XmlFileType_MatchArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Details.
        /// </summary>
        public static string XmlFileType_MatchDetails {
            get {
                return ResourceManager.GetString("XmlFileType_MatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string XmlFileType_Matches {
            get {
                return ResourceManager.GetString("XmlFileType_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Line-up.
        /// </summary>
        public static string XmlFileType_MatchLineUp {
            get {
                return ResourceManager.GetString("XmlFileType_MatchLineUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Details.
        /// </summary>
        public static string XmlFileType_PlayerDetails {
            get {
                return ResourceManager.GetString("XmlFileType_PlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string XmlFileType_Players {
            get {
                return ResourceManager.GetString("XmlFileType_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Avatars.
        /// </summary>
        public static string XmlFileType_StaffAvatars {
            get {
                return ResourceManager.GetString("XmlFileType_StaffAvatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff List.
        /// </summary>
        public static string XmlFileType_StaffList {
            get {
                return ResourceManager.GetString("XmlFileType_StaffList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Details.
        /// </summary>
        public static string XmlFileType_TeamDetails {
            get {
                return ResourceManager.GetString("XmlFileType_TeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Details.
        /// </summary>
        public static string XmlFileType_WorldDetails {
            get {
                return ResourceManager.GetString("XmlFileType_WorldDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Avatars.
        /// </summary>
        public static string XmlFileType_YouthAvatars {
            get {
                return ResourceManager.GetString("XmlFileType_YouthAvatars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth League Details.
        /// </summary>
        public static string XmlFileType_YouthLeagueDetails {
            get {
                return ResourceManager.GetString("XmlFileType_YouthLeagueDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth League Fixtures.
        /// </summary>
        public static string XmlFileType_YouthLeagueFixtures {
            get {
                return ResourceManager.GetString("XmlFileType_YouthLeagueFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Player Details.
        /// </summary>
        public static string XmlFileType_YouthPlayerDetails {
            get {
                return ResourceManager.GetString("XmlFileType_YouthPlayerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Players.
        /// </summary>
        public static string XmlFileType_YouthPlayerList {
            get {
                return ResourceManager.GetString("XmlFileType_YouthPlayerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Team Details.
        /// </summary>
        public static string XmlFileType_YouthTeamDetails {
            get {
                return ResourceManager.GetString("XmlFileType_YouthTeamDetails", resourceCulture);
            }
        }
    }
}
