//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyperar.HUM.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyperar.HUM.Globalization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have entered the Verification Code, click on &apos;Authorize&apos;..
        /// </summary>
        public static string AuthorizeMessage {
            get {
                return ResourceManager.GetString("AuthorizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hattrick will be provide you with a Verification Code.
        ///Copy the code and paste it below, making sure there aren&apos;t any blank spaces..
        /// </summary>
        public static string CopyAndPasteVerificationCodeMessage {
            get {
                return ResourceManager.GetString("CopyAndPasteVerificationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If at any point you want to stop using Hattrick Ultimate Manager, you can de-authorize it using the &apos;De-authorize&apos; button..
        /// </summary>
        public static string DeAuthorizeMessage {
            get {
                return ResourceManager.GetString("DeAuthorizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DownloadTaskStatus_Downloaded {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DownloadTaskStatus_Parsed {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Parsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DownloadTaskStatus_Pending {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DownloadTaskStatus_Processed {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DownloadTaskStatus_Started {
            get {
                return ResourceManager.GetString("DownloadTaskStatus_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Profiles found..
        /// </summary>
        public static string NoUserProfilesFound {
            get {
                return ResourceManager.GetString("NoUserProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to use Hattrick Ultimate Manager, first you have to authorize it. Click on &apos;Open Authorization Web Page&apos; to begin..
        /// </summary>
        public static string OpenAuthorizationWebPageMessage {
            get {
                return ResourceManager.GetString("OpenAuthorizationWebPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unverified.
        /// </summary>
        public static string Unverified {
            get {
                return ResourceManager.GetString("Unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
    }
}
